name: Ansible Lint

on:
    push:
        paths:
            - '**/ansible/**'
            - '**/*.yml'
            - '**/*.yaml'

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
